spring.application.name=service_api
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:52000/api_hero
spring.datasource.username=api_hero
spring.datasource.password=local_analytics_password

spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true