version: "0.2"
name: "vlees_schraper_proto"

services:
  data_collector:
    image: meatscraper/fastapi-serverless
    container_name: data_collector-app
    shm_size: "1gb"
    build:
      context: .
      dockerfile: "data_collector/Dockerfile"
    env_file:
      - .env
    environment:
      - Hond=${Hond}
      - HOST=${HOST}
      - PORT=${PORT}
      - PASSWORD=${PASSWORD}
      - USER_NAME=${USER_NAME}
      - DATABASE=${DATABASE}
      - DRIVER=${DRIVER}
    ports:
      - "8000:8000"