version: "1.0"

services:
  db:
    image: "postgres"
    shm_size: "200mb"
    restart: always
    environment:
      - POSTGRES_USER=hero
      - POSTGRES_PASSWORD=localpassword
    ports:
      - "50000:5432"

  test_db:
    image: "postgres"
    shm_size: "200mb"
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test_password
    ports:
      - "51000:5432"

  analytics_db:
    image: "postgres"
    shm_size: "300mb"
    restart: always
    environment:
      - POSTGRES_USER=api_hero
      - POSTGRES_PASSWORD=local_analytics_password
    ports:
      - "52000:5432"
  adminer:
    image: adminer
    ports:
      - 8080:8080