version: "1.0"

services:
  db:
    image: "postgres"
    shm_size: "200mb"
    restart: always
    environment:
      - POSTGRES_USER=hero
      - POSTGRES_PASSWORD=localpassword
    ports:
      - "50000:5432"

  test_db:
    image: "postgres"
    shm_size: "200mb"
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test_password
    ports:
      - "51000:5432"

  analytics_db:
    image: "postgres"
    shm_size: "300mb"
    restart: always
    environment:
      - POSTGRES_USER=api_hero
      - POSTGRES_PASSWORD=local_analytics_password
    ports:
      - "52000:5432"
  local_broker:
    image: apache/kafka:latest
    container_name: butcher_broker
    ports:
      - 29092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      # Configures the listener for your local machine on port 29092
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:29092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      # KRaft cluster configuration
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093

  adminer:
    image: adminer
    ports:
      - 8080:8080